language: node_js
node_js:
  - "4"
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower karma grunt-cli jshint jasmine-core'
  - 'npm install'
  - 'bower install'
  - 'gem install sass --version "=3.4.18"'
  - 'gem install compass --version "=1.0.3"'

after_script:
  - 'grunt build'
